import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { 
  Lock, AlertTriangle, Copy, Check, ShieldAlert, ShieldCheck, 
  Code, Zap, FileText, Layers, Key
} from 'lucide-react';

interface ApiParameter {
  name: string;
  type: string;
  required?: boolean;
  defaultValue?: string;
  description?: string;
}

interface ApiEndpointData {
  id: string;
  name: string;
  method: string;
  endpointPath: string;
  connectionId?: string;
  sqlQuery?: string;
  parameters?: string;
  enablePagination?: boolean;
  isPublic?: boolean;
  authToken?: string;
  createdAt?: string;
  updatedAt?: string;
}

interface ApiShareDocViewProps {
  token: string;
}

function getAutoGeneratedDescription(name: string, type?: string): string {
  if (!name || !name.trim()) return "Query parameter filter";
  const cleanName = name.toLowerCase().replace(/^[:_]+/, "");
  if (cleanName === "id" || cleanName.endsWith("_id")) {
    const target = cleanName === "id" ? "record" : cleanName.replace("_id", "").replace(/_/g, " ");
    return `Unique identifier filter for target ${target}`;
  }
  if (cleanName === "search" || cleanName === "q" || cleanName === "keyword" || cleanName.includes("search")) {
    return "Search query keyword to filter matching records";
  }
  if (cleanName === "status" || cleanName.endsWith("_status")) {
    return "Status state filter parameter";
  }
  if (cleanName.includes("date") || cleanName.includes("time") || cleanName.includes("created") || cleanName.includes("updated")) {
    return `Date filter constraint parameter (${type || "string"})`;
  }
  if (cleanName === "limit" || cleanName === "size") {
    return "Maximum number of records to return per request";
  }
  if (cleanName === "offset" || cleanName === "page") {
    return "Pagination offset or page number for result set";
  }
  return `Filter parameter for ${name} (${type || "string"})`;
}

export const ApiShareDocView: React.FC<ApiShareDocViewProps> = ({ token }) => {
  const [loading, setLoading] = useState(true);
  const [expired, setExpired] = useState(false);
  const [expiredMessage, setExpiredMessage] = useState('');
  const [endpoint, setEndpoint] = useState<ApiEndpointData | null>(null);
  const [baseUrl, setBaseUrl] = useState('');
  const [activeTab, setActiveTab] = useState<'curl' | 'javascript' | 'python' | 'postman'>('curl');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  useEffect(() => {
    let isMounted = true;
    axios.get(`/api/share/${token}`)
      .then(res => {
        if (!isMounted) return;
        if (res.data && res.data.valid) {
          setEndpoint(res.data.endpoint);
          setBaseUrl(res.data.baseUrl || window.location.origin);
        } else {
          setExpired(true);
          setExpiredMessage(res.data?.message || 'This share link has already been used or has expired.');
        }
      })
      .catch(err => {
        if (!isMounted) return;
        setExpired(true);
        setExpiredMessage(err.response?.data?.message || 'Failed to load specification. Link may be invalid or expired.');
      })
      .finally(() => {
        if (isMounted) setLoading(false);
      });

    return () => { isMounted = false; };
  }, [token]);

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopiedKey(key);
      setToastMessage('Copied to clipboard!');
      setTimeout(() => setCopiedKey(null), 2000);
      setTimeout(() => setToastMessage(null), 3000);
    }).catch(err => {
      console.error('Failed to copy', err);
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0b1120] text-slate-100 flex flex-col items-center justify-center p-4">
        <div className="w-10 h-10 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mb-4" />
        <p className="text-slate-400 text-sm font-medium">Loading API Specification...</p>
      </div>
    );
  }

  if (expired || !endpoint) {
    return (
      <div className="min-h-screen bg-[#0b1120] text-slate-100 flex flex-col items-center justify-center p-4 font-sans">
        <div className="max-w-md w-full bg-[#0f172a] border border-slate-800 rounded-2xl p-8 text-center shadow-2xl animate-in fade-in zoom-in-95 duration-200">
          <div className="w-16 h-16 bg-red-500/10 border border-red-500/20 rounded-2xl flex items-center justify-center mx-auto mb-5 text-red-400 shadow-inner">
            <Lock className="w-8 h-8" />
          </div>
          <h1 className="text-2xl font-bold text-slate-100 mb-2">Link Expired</h1>
          <p className="text-slate-400 text-sm leading-relaxed mb-6">
            {expiredMessage || 'This share link has already been used or has expired.'}
          </p>
          <div className="p-3 bg-slate-900/60 border border-slate-800 rounded-xl text-xs text-slate-500">
            For security, API share documentation links can only be accessed once.
          </div>
        </div>
      </div>
    );
  }

  // Parse parameters
  let parsedParams: ApiParameter[] = [];
  try {
    if (endpoint.parameters && endpoint.parameters.trim() !== '' && endpoint.parameters !== '[]') {
      const raw = JSON.parse(endpoint.parameters);
      if (Array.isArray(raw)) {
        parsedParams = raw.map((p: any) => ({
          name: p.name || '',
          type: p.type || 'string',
          required: Boolean(p.required),
          defaultValue: p.defaultValue || '',
          description: p.description && p.description.trim() ? p.description.trim() : getAutoGeneratedDescription(p.name, p.type)
        }));
      }
    }
  } catch (e) {
    console.error('Failed to parse parameters', e);
  }

  // Method styling
  const getMethodStyle = (method: string) => {
    switch (method.toUpperCase()) {
      case 'GET':
        return { badge: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30', headerBg: 'bg-emerald-600' };
      case 'POST':
        return { badge: 'bg-blue-500/15 text-blue-400 border-blue-500/30', headerBg: 'bg-blue-600' };
      case 'PUT':
        return { badge: 'bg-amber-500/15 text-amber-400 border-amber-500/30', headerBg: 'bg-amber-600' };
      case 'PATCH':
        return { badge: 'bg-purple-500/15 text-purple-400 border-purple-500/30', headerBg: 'bg-purple-600' };
      case 'DELETE':
        return { badge: 'bg-red-500/15 text-red-400 border-red-500/30', headerBg: 'bg-red-600' };
      default:
        return { badge: 'bg-slate-500/15 text-slate-400 border-slate-500/30', headerBg: 'bg-slate-600' };
    }
  };

  const methodStyle = getMethodStyle(endpoint.method);

  // Compute full endpoint URL
  const origin = baseUrl || window.location.origin;
  const fullEndpointUrl = `${origin}/api/data${endpoint.endpointPath}`;
  const domain = origin.replace(/^https?:\/\//, '');

  // Code Snippet URL & Parameters
  const hasParams = parsedParams.length > 0;
  let queryString = '';
  if (endpoint.method.toUpperCase() === 'GET') {
    if (hasParams || endpoint.enablePagination) {
      const parts: string[] = [];
      if (hasParams) parts.push(`${parsedParams[0].name}=value`);
      if (endpoint.enablePagination) parts.push('limit=10&page=1');
      if (parts.length > 0) queryString = '?' + parts.join('&');
    }
  }
  const snippetUrl = fullEndpointUrl + queryString;
  const isPublic = Boolean(endpoint.isPublic);

  // Code Snippets
  const authHeaderLine = !isPublic && endpoint.authToken ? `  -H "Authorization: Bearer ${endpoint.authToken}"` : '';
  const postmanAuthLine = !isPublic && endpoint.authToken ? `\nAuthorization: Bearer ${endpoint.authToken}` : '';
  const jsAuthLine = !isPublic && endpoint.authToken ? `\n    "Authorization": "Bearer ${endpoint.authToken}",` : '';
  const pythonAuthLine = !isPublic && endpoint.authToken ? `\n    "Authorization": "Bearer ${endpoint.authToken}",` : '';

  const curlCode = `curl -X ${endpoint.method.toUpperCase()} "${snippetUrl}" \\
  -H "Accept: application/json"${authHeaderLine ? ' \\\n' + authHeaderLine : ''}${
    endpoint.method.toUpperCase() !== 'GET' && hasParams
      ? ` \\\n  -H "Content-Type: application/json" \\\n  -d '{\n    "${parsedParams[0]?.name || 'param'}": "value"\n  }'`
      : ''
  }`;

  const jsCode = `const response = await fetch("${snippetUrl}", {
  method: "${endpoint.method.toUpperCase()}",
  headers: {
    "Accept": "application/json",${jsAuthLine}${
      endpoint.method.toUpperCase() !== 'GET' ? '\n    "Content-Type": "application/json"\n  },' : '\n  }'
    }${
      endpoint.method.toUpperCase() !== 'GET'
        ? `\n  body: JSON.stringify({\n    "${parsedParams[0]?.name || 'param'}": "value"\n  })`
        : ''
    }
});
const data = await response.json();`;

  const pythonCode = `import requests

url = "${snippetUrl}"
headers = {
    "Accept": "application/json",${pythonAuthLine}${
      endpoint.method.toUpperCase() !== 'GET' ? '\n    "Content-Type": "application/json"\n}' : '\n}'
    }${
      endpoint.method.toUpperCase() !== 'GET'
        ? `\npayload = {\n    "${parsedParams[0]?.name || 'param'}": "value"\n}\nresponse = requests.${endpoint.method.toLowerCase()}(url, headers=headers, json=payload)`
        : `\nresponse = requests.${endpoint.method.toLowerCase()}(url, headers=headers)`
    }
print(response.json())`;

  const postmanCode = `${endpoint.method.toUpperCase()} ${snippetUrl} HTTP/1.1
Host: ${domain}
Accept: application/json${postmanAuthLine}${
    endpoint.method.toUpperCase() !== 'GET'
      ? `\nContent-Type: application/json\n\n{\n  "${parsedParams[0]?.name || 'param'}": "value"\n}`
      : ''
  }`;

  const snippetMap = {
    curl: curlCode,
    javascript: jsCode,
    python: pythonCode,
    postman: postmanCode
  };

  return (
    <div className="min-h-screen bg-[#0b1120] text-slate-100 font-sans selection:bg-blue-500 selection:text-white pb-20">
      <div className="max-w-4xl mx-auto px-4 py-8 md:py-12">

        {/* Warning Banner */}
        <div className="mb-8 p-4 bg-amber-500/10 border border-amber-500/25 rounded-2xl flex items-start gap-3 text-amber-300 text-sm shadow-lg shadow-amber-500/5">
          <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5 text-amber-400" />
          <div>
            <strong className="font-semibold text-amber-200">One-time share link.</strong> This documentation link is for single-use and will expire once opened. Save any necessary information now.
          </div>
        </div>

        {/* Header Section */}
        <div className="mb-8">
          <div className="flex items-center gap-2 mb-3">
            <span className="px-2.5 py-1 text-xs font-semibold rounded-md bg-blue-500/10 text-blue-400 border border-blue-500/20">
              API Documentation
            </span>
            {isPublic ? (
              <span className="px-2.5 py-1 text-xs font-semibold rounded-md bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 flex items-center gap-1">
                <ShieldCheck className="w-3.5 h-3.5" /> Public Access
              </span>
            ) : (
              <span className="px-2.5 py-1 text-xs font-semibold rounded-md bg-amber-500/10 text-amber-400 border border-amber-500/20 flex items-center gap-1">
                <ShieldAlert className="w-3.5 h-3.5" /> Bearer Token Required
              </span>
            )}
          </div>
          <h1 className="text-3xl md:text-4xl font-extrabold text-slate-100 tracking-tight mb-2">
            {endpoint.name}
          </h1>
          <p className="text-slate-400 text-base">
            API Specification Documentation
          </p>
        </div>

        {/* Endpoint Configuration Section */}
        <section className="bg-[#0f172a] border border-slate-800 rounded-2xl p-6 mb-6 shadow-xl">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-4 flex items-center gap-2">
            <Zap className="w-4 h-4 text-blue-400" /> Endpoint Configuration
          </h2>
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center bg-[#0b1120] border border-slate-800 rounded-xl overflow-hidden">
            <div className={`px-4 py-3 text-xs font-black tracking-widest text-white uppercase text-center ${methodStyle.headerBg}`}>
              {endpoint.method}
            </div>
            <div className="px-4 py-3 font-mono text-sm text-cyan-400 flex-1 overflow-x-auto whitespace-nowrap">
              {fullEndpointUrl}
            </div>
            <button
              onClick={() => copyToClipboard(fullEndpointUrl, 'url')}
              className="px-4 py-3 bg-slate-800/80 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-colors flex items-center justify-center gap-2 border-t sm:border-t-0 sm:border-l border-slate-800 shrink-0"
            >
              {copiedKey === 'url' ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copiedKey === 'url' ? 'Copied' : 'Copy URL'}</span>
            </button>
          </div>
        </section>

        {/* Authentication Section */}
        <section className="bg-[#0f172a] border border-slate-800 rounded-2xl p-6 mb-6 shadow-xl">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-4 flex items-center gap-2">
            <Key className="w-4 h-4 text-blue-400" /> Authentication
          </h2>
          {isPublic ? (
            <div className="p-4 bg-emerald-500/5 border border-emerald-500/20 rounded-xl flex items-start gap-3">
              <ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
              <div>
                <h4 className="text-sm font-semibold text-emerald-300 mb-1">Public Endpoint</h4>
                <p className="text-xs text-slate-400">No authorization headers are required to access this endpoint.</p>
              </div>
            </div>
          ) : (
            <div className="p-4 bg-amber-500/5 border border-amber-500/20 rounded-xl">
              <div className="flex items-center gap-2 text-amber-300 font-semibold text-sm mb-2">
                <ShieldAlert className="w-4 h-4 text-amber-400" /> Protected Endpoint
              </div>
              <p className="text-xs text-slate-400 mb-3">Include the following header in your HTTP requests:</p>
              <div className="flex items-center bg-[#0b1120] border border-amber-500/30 rounded-xl overflow-hidden">
                <code className="px-4 py-2.5 font-mono text-xs text-amber-300 flex-1 overflow-x-auto">
                  Authorization: Bearer {endpoint.authToken || 'YOUR_TOKEN'}
                </code>
                <button
                  onClick={() => copyToClipboard(`Authorization: Bearer ${endpoint.authToken}`, 'auth')}
                  className="px-3.5 py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-colors flex items-center gap-1.5 border-l border-slate-800 shrink-0"
                >
                  {copiedKey === 'auth' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedKey === 'auth' ? 'Copied' : 'Copy'}</span>
                </button>
              </div>
            </div>
          )}
        </section>

        {/* Parameters Section */}
        <section className="bg-[#0f172a] border border-slate-800 rounded-2xl p-6 mb-6 shadow-xl">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-4 flex items-center gap-2">
            <Layers className="w-4 h-4 text-blue-400" /> Parameters
          </h2>

          {parsedParams.length > 0 ? (
            <div className="border border-slate-800 rounded-xl overflow-hidden mb-4">
              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead>
                    <tr className="bg-[#0b1120] text-slate-400 border-b border-slate-800 uppercase tracking-wider text-[11px]">
                      <th className="py-3 px-4">Name</th>
                      <th className="py-3 px-4">Type</th>
                      <th className="py-3 px-4">Required</th>
                      <th className="py-3 px-4">Default</th>
                      <th className="py-3 px-4">Description</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-800/60">
                    {parsedParams.map((p, idx) => (
                      <tr key={idx} className="hover:bg-slate-800/30 transition-colors">
                        <td className="py-3 px-4 font-mono text-cyan-400 font-semibold">{p.name}</td>
                        <td className="py-3 px-4 text-slate-300 capitalize">{p.type}</td>
                        <td className="py-3 px-4">
                          {p.required ? (
                            <span className="px-2 py-0.5 text-[10px] font-bold uppercase rounded bg-red-500/15 text-red-400 border border-red-500/30">
                              Required
                            </span>
                          ) : (
                            <span className="px-2 py-0.5 text-[10px] font-bold uppercase rounded bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                              Optional
                            </span>
                          )}
                        </td>
                        <td className="py-3 px-4 font-mono text-slate-400">{p.defaultValue || '—'}</td>
                        <td className="py-3 px-4 text-slate-300 leading-relaxed">{p.description}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ) : (
            <p className="text-xs text-slate-400 italic py-2">No custom query parameters required for this endpoint.</p>
          )}

          {/* Pagination Card */}
          {endpoint.enablePagination && (
            <div className="mt-4 p-5 bg-blue-500/5 border border-blue-500/20 rounded-2xl">
              <div className="flex items-start gap-3">
                <div className="text-2xl leading-none">⚡</div>
                <div className="flex-1">
                  <h4 className="text-sm font-bold text-blue-400 mb-1">Cara Penggunaan Pagination (Query Parameters)</h4>
                  <p className="text-xs text-slate-400 leading-relaxed mb-3">
                    Endpoint ini mendukung fitur <strong>Pagination</strong> otomatis. Anda dapat menambahkan parameter <code className="text-blue-300 font-mono bg-blue-500/10 px-1 py-0.5 rounded">limit</code> dan <code className="text-blue-300 font-mono bg-blue-500/10 px-1 py-0.5 rounded">page</code> pada URL:
                  </p>
                  <div className="border border-slate-800 rounded-xl overflow-hidden mb-3">
                    <table className="w-full text-left text-xs">
                      <thead>
                        <tr className="bg-[#0b1120] text-blue-300/90 border-b border-slate-800">
                          <th className="p-2.5">Parameter</th>
                          <th className="p-2.5">Default</th>
                          <th className="p-2.5">Penjelasan & Cara Kerja</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-800/60 text-slate-300">
                        <tr>
                          <td className="p-2.5 font-mono text-blue-400 font-bold">limit</td>
                          <td className="p-2.5 font-mono text-slate-400">100</td>
                          <td className="p-2.5">Jumlah baris data maksimal yang diambil per request. Misal: <code className="text-cyan-300 font-mono bg-slate-900 px-1 rounded">?limit=10</code> (Maksimal: 1000).</td>
                        </tr>
                        <tr>
                          <td className="p-2.5 font-mono text-blue-400 font-bold">page</td>
                          <td className="p-2.5 font-mono text-slate-400">1</td>
                          <td className="p-2.5">Nomor halaman yang ingin diambil (dimulai dari 1). Misal: <code className="text-cyan-300 font-mono bg-slate-900 px-1 rounded">?page=1</code> (data 1-10), <code className="text-cyan-300 font-mono bg-slate-900 px-1 rounded">?page=2</code> (data 11-20).</td>
                        </tr>
                        <tr>
                          <td className="p-2.5 font-mono text-blue-400 font-bold">offset</td>
                          <td className="p-2.5 font-mono text-slate-400">0</td>
                          <td className="p-2.5">Alternatif pengganti <code>page</code>. Menentukan berapa baris data yang diloncati. Misal: <code className="text-cyan-300 font-mono bg-slate-900 px-1 rounded">?offset=20&limit=10</code>.</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div className="bg-[#0b1120] border border-slate-800 rounded-xl p-3 font-mono text-xs leading-relaxed text-blue-300">
                    <div className="font-bold text-sky-400 mb-1">📌 Contoh URL Siap Pakai:</div>
                    <div className="text-slate-300">• Halaman 1 (10 Data): <code className="text-pink-400">{fullEndpointUrl}?limit=10&page=1</code></div>
                    <div className="text-slate-300">• Halaman 2 (10 Data): <code className="text-pink-400">{fullEndpointUrl}?limit=10&page=2</code></div>
                    <div className="text-slate-300">• Halaman 3 (50 Data): <code className="text-pink-400">{fullEndpointUrl}?limit=50&page=3</code></div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </section>

        {/* Code Example Section */}
        <section className="bg-[#0f172a] border border-slate-800 rounded-2xl p-6 mb-6 shadow-xl">
          <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 flex items-center gap-2">
              <Code className="w-4 h-4 text-blue-400" /> Code Snippets
            </h2>
            <div className="flex items-center bg-[#0b1120] border border-slate-800 rounded-xl p-1 gap-1">
              {(['curl', 'javascript', 'python', 'postman'] as const).map(tab => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-all capitalize ${
                    activeTab === tab 
                      ? 'bg-blue-600 text-white shadow-md' 
                      : 'text-slate-400 hover:text-slate-200'
                  }`}
                >
                  {tab === 'curl' ? 'cURL' : tab === 'javascript' ? 'JavaScript' : tab === 'python' ? 'Python' : 'Postman'}
                </button>
              ))}
            </div>
          </div>

          <div className="relative bg-[#0b1120] border border-slate-800 rounded-xl p-4 overflow-x-auto">
            <button
              onClick={() => copyToClipboard(snippetMap[activeTab], 'snippet')}
              className="absolute top-3 right-3 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5 border border-slate-700 shadow-md"
            >
              {copiedKey === 'snippet' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedKey === 'snippet' ? 'Copied' : 'Copy'}</span>
            </button>
            <pre className="font-mono text-xs text-slate-200 leading-relaxed pr-16">
              <code>{snippetMap[activeTab]}</code>
            </pre>
          </div>
        </section>

        {/* Response Format Section */}
        <section className="bg-[#0f172a] border border-slate-800 rounded-2xl p-6 shadow-xl">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2 flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-400" /> Response Format
          </h2>
          <p className="text-xs text-slate-400 mb-4">
            The API responds with <code className="text-cyan-400 font-mono">application/json</code> payloads.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* 200 OK */}
            <div className="border border-emerald-500/30 rounded-xl overflow-hidden bg-[#0b1120]">
              <div className="bg-emerald-500/10 border-b border-emerald-500/20 px-4 py-2.5 flex items-center justify-between text-emerald-400 font-bold text-xs">
                <span>200 OK</span>
                <span className="text-[10px] font-normal text-emerald-400/80">Success</span>
              </div>
              <pre className="p-4 font-mono text-xs text-slate-300 overflow-x-auto">
                <code>{`[\n  {\n    "column1": "value1",\n    "column2": "value2"\n  }\n]`}</code>
              </pre>
            </div>

            {/* Error */}
            <div className="border border-red-500/30 rounded-xl overflow-hidden bg-[#0b1120]">
              <div className="bg-red-500/10 border-b border-red-500/20 px-4 py-2.5 flex items-center justify-between text-red-400 font-bold text-xs">
                <span>400 / 401 / 500</span>
                <span className="text-[10px] font-normal text-red-400/80">Error Response</span>
              </div>
              <pre className="p-4 font-mono text-xs text-slate-300 overflow-x-auto">
                <code>{`{\n  "error": "Error message description"\n}`}</code>
              </pre>
            </div>
          </div>
        </section>

      </div>

      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 bg-blue-600 text-white px-4 py-3 rounded-xl shadow-2xl text-xs font-semibold flex items-center gap-2 animate-in slide-in-from-bottom duration-200 z-50">
          <Check className="w-4 h-4 text-emerald-300" />
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
};
