server.port=8081

# Primary database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/datasync_studio
spring.datasource.username=postgres
spring.datasource.password=Awanda213
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize schema
spring.sql.init.mode=always

# Increase async request timeout to 1 hour (3600000 ms) for large streaming requests
spring.mvc.async.request-timeout=3600000
